before_build:
  - echo "Downloading precompiled dependencies"
  - uname
  - uname -m
  - curl -c ./cookie.txt -s -L "https://drive.google.com/uc?export=download&id=1mgeaL_vKnKnbLDRVa3AsbPh_AUfuYg5a" > tmp.txt
  - grep -v DOCTYPE tmp.txt > tmp2.txt
  - cat tmp2.txt
  - ls
#  - sed -e 's/.*\(uc?export.*\)">Download anywa.*/\1/' tmp2.txt > tmp.txt
#  - cat tmp.txt
#  - sed -e 's/amp;//g' tmp.txt > tmp2.txt
#  - cat tmp2.txt
#  - export req=$(cat tmp2.txt)
#  - echo $req
#  - echo "https://drive.google.com$req"
#  - curl -b ./cookie.txt -o yacoindependencies.zip -s -L "https://drive.google.com/$req"
#  - 7z x yacoindependencies.zip
#  - md yacoindeps
#  - cd yacoindeps
#  - md sw
#  - cd sw
#  - mv ../../YacoinDependencies/* .

build_script:
  - echo building
  - pwd
  - cd utils
  - echo $PATH
  - sh ./build.sh

after_build:
  - echo AFTER BUILD
  - pwd