before_build:
  - |-
    echo "Downloading precompiled dependencies"
    uname
    uname -m
    pwd
    curl -c ./cookie.txt -s -L "https://drive.google.com/uc?export=download&id=1tzi3SR9bZ_QCF3uRTH2VjSRsuuBWBVd9" > tmp.txt
    grep -v DOCTYPE tmp.txt > tmp2.txt
    cat tmp2.txt
    ls
    sed -e 's/.*confirm=/confirm=/' tmp2.txt > tmp3.txt
    cat tmp3.txt
    sed -e 's/&id=.*//' tmp3.txt > tmp4.txt
    cat tmp4.txt
    export req=$(cat tmp4.txt)
    echo $req
    echo "https://drive.google.com//uc?export=download&id=1tzi3SR9bZ_QCF3uRTH2VjSRsuuBWBVd9&$req"
    curl -b ./cookie.txt -o yacoindependencies.zip -s -L "https://drive.google.com//uc?export=download&id=1tzi3SR9bZ_QCF3uRTH2VjSRsuuBWBVd9&$req"
    7z x yacoindeps.zip
    cd yacoindeps/sw/
    sed -e 's/REPLACEPATH/\/c\/projects' yconf > yconf2
    mv yconf2 yconf

build_script:
  - echo building
  - pwd
  - cd utils
  - echo $PATH
  - sh ./build.sh

after_build:
  - echo AFTER BUILD
  - pwd