matrix:
    fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
    allow_failures:
      - platform: x64
        configuration: Release

build_script:
    - ps: Invoke-WebRequest -Uri "https://github.com/git-for-windows/git/releases/download/v2.8.2.windows.1/PortableGit-2.8.2-32-bit.7z.exe" -OutFile "gitlab-portable.exe"