name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: pullyacoindocker
        run: |
          echo someoutput
          pwd
          echo $(pwd)
          docker pull dev34253/yacoin-build:ubuntu.16.04
          docker run -v ${pwd}:/src dev34253/yacoin-build:ubuntu.16.04
