name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps: |
      - name: pullyacoindocker
        run: docker pull dev34253/yacoind:0.4.9
      - name: buildyacoin
        run: docker run -v $(pwd):/ysrc dev34253/yacoind:0.4.9 "cd /ysrc && ./autogen.sh && ./configure && make"
