name: C/C++ CI

on: [push]

jobs:
  build-ubuntu-1604:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: pullyacoindocker
        run: |
          docker pull dev34253/yacoin-build:ubuntu.16.04
          docker run -v /home/runner/work/yacoin/yacoin:/src dev34253/yacoin-build:ubuntu.16.04
      - uses: actions/upload-artifact@v1
        with:
          name: yacoind-ubuntu-16.04
          path: /home/runner/work/yacoin/yacoin/src/yacoind
  build-ubuntu-1804:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: pullyacoindocker
        run: |
          docker pull dev34253/yacoin-build:ubuntu.18.04
          docker run -v /home/runner/work/yacoin/yacoin:/src dev34253/yacoin-build:ubuntu.18  .04
      - uses: actions/upload-artifact@v1
          with:
            name: yacoind-ubuntu-18.04
            path: /home/runner/work/yacoin/yacoin/src/yacoind
