name: Yacoin multi platform build

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest  
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker pull dev34253/yacoin-build:windows.latest
          docker tag dev34253/yacoin-build:windows.latest yacoin/yacoin-build:windows.latest
          echo "${{secrets.DOCKER_YACPWD}}" | docker login -u yacoin --password-stdin
          docker push yacoin/yacoin-build:windows.latest
        shell: cmd
